"use server"
  

export async function generateAnswer(question, settings) {
  // In a real application, this would call an AI API like OpenAI
  // For demo purposes, we'll simulate a response based on the question

  await new Promise((resolve) => setTimeout(resolve, 200)) // Simulate API delay

  // Example answers based on common questions
  let answer = ""

  if (question.toLowerCase().includes("tell me about yourself")) {
    answer =
      'When answering "Tell me about yourself" in an interview, follow this structure:\n\n1. **Present**: Start with your current role and responsibilities\n   - "I\'m currently a Senior Software Engineer at XYZ Company, where I lead a team developing cloud-based solutions."\n\n2. **Past**: Briefly mention relevant past experiences\n   - "Before that, I spent three years at ABC Corp, where I helped build their core platform and improved deployment time by 40%."\n\n3. **Future**: Express your interest in the role you\'re interviewing for\n   - "I\'m now looking to bring my technical leadership and cloud expertise to a larger organization like yours."\n\n4. **Skills & Value**: Highlight key skills relevant to the position\n   - "My experience with microservices architecture and team leadership has prepared me well for this Senior Developer role."\n\nKeep your answer concise (1-2 minutes) and professional. Focus on career highlights rather than personal details, unless they\'re directly relevant to the position. Tailor your response to emphasize experiences and skills that align with the job description.'
  } else if (question.toLowerCase().includes("greatest strength")) {
    answer =
      'When answering about your greatest strengths in an interview, follow these guidelines:\n\n1. **Be relevant**: Choose strengths that align with the job requirements\n\n2. **Be specific**: Don\'t just say "I\'m a good communicator" - explain what makes your communication skills strong\n\n3. **Provide evidence**: Back up your claims with concrete examples\n\n4. **Be honest**: Choose genuine strengths you can speak about confidently\n\n**Example Answer:**\n"One of my greatest strengths is my ability to translate complex technical concepts into clear, accessible language. As a senior developer at my previous company, I regularly presented technical updates to non-technical stakeholders. For instance, I created a visual dashboard that helped our marketing team understand our product\'s technical capabilities, which improved our cross-departmental collaboration and led to a 25% increase in feature adoption. This skill would be valuable in this role where technical teams need to work closely with other departments."\n\nAvoid generic strengths like "hard worker" or "team player" without specific examples. Also, ensure your strengths genuinely match what the employer is seeking.'
  } else if (question.toLowerCase().includes("why do you want to work here")) {
    answer =
      'When answering "Why do you want to work here?" in an interview, follow these key strategies:\n\n1. **Research the company thoroughly**\n   - Study their mission, values, products/services, culture, and recent news\n   - Review their social media and employee reviews\n\n2. **Connect your values and goals to the company**\n   - "Your company\'s commitment to sustainability aligns with my personal values..."\n   - "I\'m impressed by your innovative approach to [specific product/service]..."\n\n3. **Highlight specific aspects that attract you**\n   - Company culture or values\n   - Products or services you admire\n   - Growth opportunities or learning potential\n   - Company reputation or achievements\n\n4. **Show how you can contribute**\n   - "My experience in [relevant skill] would allow me to contribute to your mission of..."\n   - "I\'m excited about applying my background in [area] to help advance your work in [company initiative]..."\n\n**Example Answer:**\n"I want to work at Acme Tech because your commitment to developing AI solutions that prioritize ethical considerations aligns perfectly with my professional values. I\'ve followed your company\'s growth over the past three years and was particularly impressed by your recent project that helped reduce energy consumption in data centers by 30%. My background in machine learning optimization would allow me to contribute to these initiatives while growing my skills in an environment that clearly values both innovation and responsibility. I\'m also drawn to your collaborative culture—several of your employees have mentioned the supportive team environment in my informational interviews."\n\nAvoid generic answers that could apply to any company or focusing solely on what you\'ll gain rather than what you\'ll contribute.'
  } else if (question.toLowerCase().includes("5 years")) {
    answer =
      "When answering \"Where do you see yourself in 5 years?\" in an interview, follow these guidelines:\n\n1. **Be realistic yet ambitious**\n   - Show growth aspirations that are achievable within the company\n   - Demonstrate you understand typical career progression in your field\n\n2. **Connect to the current role**\n   - Explain how the position you're interviewing for fits into your career path\n   - Show how it provides the foundation for your future goals\n\n3. **Show commitment and loyalty**\n   - Express interest in growing with the company long-term\n   - Avoid suggesting you'll use this job merely as a stepping stone\n\n4. **Emphasize skill development**\n   - Mention specific skills or expertise you hope to develop\n   - Show you're proactive about professional growth\n\n**Example Answer:**\n\"In five years, I envision myself having grown into a senior role with deeper expertise in cloud architecture and possibly leading a small team. I'm particularly interested in developing my skills in serverless technologies and distributed systems, which I know are important for your company's product roadmap. I'm excited about the learning opportunities this role provides, especially the chance to work on your microservices migration. Long-term, I hope to have contributed significantly to your technical infrastructure while continuing to expand my technical and leadership capabilities within the organization.\"\n\nAvoid:\n- Unrealistic goals (\"I want to be CEO\")\n- Vague answers (\"I'm not sure\")\n- Answers that suggest you'll quickly leave the role\n- Personal goals unrelated to your career"
  } else if (question.toLowerCase().includes("challenging situation")) {
    answer =
      'When describing a challenging situation at work and how you handled it, use the STAR method:\n\n**Situation**: Describe the specific challenging scenario you faced.\n\n**Task**: Explain your role and responsibilities in addressing the challenge.\n\n**Action**: Detail the specific steps you took to resolve the situation.\n\n**Result**: Share the positive outcomes of your actions, using metrics if possible.\n\n**Example Answer:**\n"At my previous company, we faced a critical situation when our main product experienced unexpected downtime during a major client onboarding (Situation). As the lead developer on call, I was responsible for diagnosing the issue and restoring service as quickly as possible while maintaining communication with stakeholders (Task).\n\nI immediately assembled a cross-functional team from engineering and operations, established a war room, and implemented our incident response protocol. I personally identified that the issue stemmed from an unexpected data migration conflict, then developed and deployed a hotfix while other team members handled client communications and monitored systems (Action).\n\nWe resolved the issue within 45 minutes, minimizing impact on the client. Afterward, I led a thorough post-mortem that resulted in implementing new testing protocols and monitoring systems that reduced similar incidents by 80% over the next quarter. The client was impressed with our quick response and transparent communication, and they remain one of our biggest accounts today (Result)."\n\n**Key tips:**\n- Choose a genuine challenge that demonstrates valuable skills\n- Focus on your specific actions and decisions\n- Emphasize the positive outcome and what you learned\n- Show how you remained calm and methodical under pressure\n- Highlight collaboration and communication skills'
  } else {
    answer =
      "I'll help you prepare an effective answer to this interview question.\n\n**Key considerations for answering \"" +
      question +
      '":**\n\n1. **Understand the intent**: This question is designed to assess your relevant skills, experience, and fit for the role.\n\n2. **Structure your response**: Use a clear framework like the STAR method (Situation, Task, Action, Result) if it\'s a behavioral question.\n\n3. **Be specific**: Provide concrete examples from your experience rather than generic statements.\n\n4. **Align with the job**: Tailor your answer to highlight skills and experiences relevant to this specific position.\n\n5. **Be authentic**: While preparation is important, ensure your answer genuinely reflects your experience and perspective.\n\n**Sample answer framework:**\n"When approaching this question, I would start by acknowledging the importance of [relevant skill/quality]. In my experience at [previous company], I demonstrated this by [specific example with measurable results]. This experience taught me [key lesson], which I believe would be valuable in this role because [connection to job requirements]."\n\n**Additional tips:**\n- Keep your answer concise and focused (1-2 minutes)\n- Practice your delivery but avoid sounding rehearsed\n- Be prepared for follow-up questions\n- Maintain positive framing, even when discussing challenges'
  }

  // Adjust based on settings
  if (settings.answerLength === "concise") {
    // Shorten the answer by removing some details
    answer = answer.split("\n\n").slice(0, 3).join("\n\n")
  } else if (settings.answerLength === "detailed") {
    // Add more details
    answer +=
      "\n\n**Additional considerations:**\n- Research the company culture to ensure your answer aligns with their values\n- Consider how this question relates to the specific role you're applying for\n- Prepare 2-3 variations of your answer for different interview scenarios"
  }

  return answer
}
